### ISSUE TITLE
Getting issue with the helm install

### ISSUE THREAD

**Issue by vsaxena6** [Azure/secrets-store-csi-driver-provider-azure#488]
Hi ,

I have installed the repo using helm install command and my secret-store driver is throwing error.
Its not coming up and thus restarts each time.
Error: 

kubectl logs csi-secrets-store-provider-azure-1619547838-secrets-store-b8lx8 secrets-store -n my-ns
I0427 18:36:15.862229       1 exporter.go:33] metrics backend: prometheus
F0427 18:36:25.899047       1 main.go:132] failed to start manager, error: an error on the server ("") has prevented the request from succeeding
goroutine 1 [running]:
k8s.io/klog/v2.stacks(0xc00000e001, 0xc0001f4000, 0x91, 0x9b)
        /go/pkg/mod/k8s.io/klog/v2@v2.5.0/klog.go:1026 +0xb9
k8s.io/klog/v2.(*loggingT).output(0x26219c0, 0xc000000003, 0x0, 0x0, 0xc00017e700, 0x1ed1099, 0x7, 0x84, 0x0)
        /go/pkg/mod/k8s.io/klog/v2@v2.5.0/klog.go:975 +0x191
k8s.io/klog/v2.(*loggingT).printf(0x26219c0, 0xc000000003, 0x0, 0x0, 0x0, 0x0, 0x19a03a7, 0x23, 0xc0004a1d90, 0x1, ...)
        /go/pkg/mod/k8s.io/klog/v2@v2.5.0/klog.go:750 +0x191
k8s.io/klog/v2.Fatalf(...)
        /go/pkg/mod/k8s.io/klog/v2@v2.5.0/klog.go:1514
main.main()
        /go/src/sigs.k8s.io/secrets-store-csi-driver/cmd/secrets-store-csi-driver/main.go:132 +0x94c

goroutine 6 [chan receive]:
k8s.io/klog/v2.(*loggingT).flushDaemon(0x26219c0)
        /go/pkg/mod/k8s.io/klog/v2@v2.5.0/klog.go:1169 +0x8b
created by k8s.io/klog/v2.init.0
        /go/pkg/mod/k8s.io/klog/v2@v2.5.0/klog.go:417 +0xdf

goroutine 7 [sleep]:
time.Sleep(0x6fc23ac00)
        /usr/local/go/src/runtime/time.go:193 +0xd2
sigs.k8s.io/controller-runtime/pkg/log.init.0.func1()
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.2/pkg/log/log.go:63 +0x45
created by sigs.k8s.io/controller-runtime/pkg/log.init.0
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.2/pkg/log/log.go:62 +0x35

Please help.

**Comment by aramase** [comment]
Could you provide more details on how you're installing and what is the cluster configuration?

1. What cluster is this? AKS/AKS-engine?
2. Kubernetes version 
3. CSI Driver and provider version
4. What are the steps taken to install?
5. `kubectl get pods -A` output?

**Comment by vsaxena6** [comment]
1. I am using AKS cluster
2. kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"**", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"****", GitTreeState:"clean", BuildDate:"2021-03-10T23:40:01Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

3. CSI Driver image used: Image:      mcr.microsoft.com/oss/kubernetes-csi/csi-node-driver-registrar:v2.1.0
4. Steps taken to install: Followed official doc: https://docs.microsoft.com/en-us/azure/key-vault/general/key-vault-integrate-kubernetes 
 helm  repo add ...
helm repo install
![image](https://user-images.githubusercontent.com/40315678/116300827-f7eb1100-a7bc-11eb-8f4d-fe6873b84022.png)

![image](https://user-images.githubusercontent.com/40315678/116300932-194bfd00-a7bd-11eb-8e88-1ec3769eacd8.png)

**Comment by aramase** [comment]
@vsaxena6 Are you using the latest helm charts to deploy the driver? It looks like there might be an issue connecting to the kube-apiserver when the client is initializing. Do you have any firewall rules or restricted egress enabled in the cluster?

If yes, could you try deploying the charts in `kube-system` namespace?

**Comment by vsaxena6** [comment]
Thanks!! It worked in kube-system. We had firewall rules applied in our AKS, that could be the reason behind failing of driver.

**Comment by vsaxena6** [comment]
Hi,
I could run the  driver in kube-system, however when I am trying to call the driver from my namespace I am getting following error:
MountVolume.SetUp failed for volume "secrets-store-inline" : kubernetes.io/csi: mounter.SetUpAt failed to get CSI client: driver name secrets-store.csi.k8s.io not found in the list of registered CSI drivers

This is how my deployment file look like:
![image](https://user-images.githubusercontent.com/40315678/116347852-a1a4bf00-a80a-11eb-9a4c-3eb536123107.png)

**Comment by vsaxena6** [comment]
Hi, 
After adding node-selector, I could see that the driver has been found by the pod, however it still fails giving following errors:

![image](https://user-images.githubusercontent.com/40315678/116350337-65c02880-a80f-11eb-803c-f7f776d41c20.png)

**Comment by patpishiva** [comment]
Hello @vsaxena6 ,
   It can be related to your network firewall rule blocking egress from the host  . 

Please take a look at the similar issue:
https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues/292
https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues/471

**Comment by aramase** [comment]
@vsaxena6 Here is our troubleshooting guide: https://azure.github.io/secrets-store-csi-driver-provider-azure/troubleshooting/

1. There is no `secretProviderClassNamespace`. The `SecretProviderClass` will be looked up from the same namespace as the pod referencing it in the volume.
2. If the mount fails, you can look at the logs from the driver and provider running on the same node as your application. Steps to retrieve the logs are in the troubleshooting guide.

**Comment by aramase** [comment]
@vsaxena6 Any updates on this? Is the issue resolved?

**Comment by aramase** [comment]
Closing this issue due to inactivity. Please feel free to reopen if this is still an ongoing issue.
