### ISSUE TITLE
Nil pointer dereference when getting a disabled certificate

### ISSUE THREAD

**Issue by pjquirk** [Azure/secrets-store-csi-driver-provider-azure#532]
**Have you**

- [x] Read [Troubleshooting Guide](https://azure.github.io/secrets-store-csi-driver-provider-azure/troubleshooting/)
- [x] Searched on [GitHub issues](https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues) and [Discussions](https://github.com/Azure/secrets-store-csi-driver-provider-azure/discussions)

**What steps did you take and what happened:**
Our deployment process failed to create a certificate in keyvault via the `az` CLI, and missed the fact that it failed.  This resulted in a certificate in the keyvault with a status of 'Disabled'.  Later in the deployment, we try to retrieve that certificate but the provider fails with a nil pointer dereference:

```
I0609 19:58:46.636353       1 provider.go:260] "fetching object from key vault" objectName="ssl-certificate" objectType="cert" keyvault="ghzf6l24nte3ufw" pod="ghae/azsecpack-initializer-mqxwb"
I0609 19:58:46.636428       1 provider.go:248] "unmarshaled key vault objects" keyVaultObjects=[<snip>] count=10 pod="ghae/telegraf-67f87fdcf5-q2spx"
I0609 19:58:46.636448       1 provider.go:260] "fetching object from key vault" objectName="actions-x-RunnerResourceGroupName" objectType="secret" keyvault="ghzf6l24nte3ufw" pod="ghae/telegraf-67f87fdcf5-q2spx"
I0609 19:58:46.636483       1 auth.go:131] "using user-assigned managed identity to retrieve access token" clientID="a7eb##### REDACTED #####0904" pod="ghae/azsecpack-initializer-mqxwb"
I0609 19:58:46.636505       1 auth.go:131] "using user-assigned managed identity to retrieve access token" clientID="a7eb##### REDACTED #####0904" pod="ghae/telegraf-67f87fdcf5-q2spx"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x99cf17]
goroutine 81 [running]:
github.com/Azure/secrets-store-csi-driver-provider-azure/pkg/provider.(*Provider).GetKeyVaultObjectContent(0xc00043b8d0, 0xbebb40, 0xc00061a0c0, 0xc000312440, 0xf, 0xc0000c8180, 0x13, 0x0, 0x0, 0xc000312478, ...)
	/agent/_work/1/s/go/src/github.com/Azure/secrets-store-csi-driver-provider-azure/pkg/provider/provider.go:428 +0x1f97
github.com/Azure/secrets-store-csi-driver-provider-azure/pkg/provider.(*Provider).MountSecretsStoreObjectContent(0xc00047d8d0, 0xbebb40, 0xc00061a0c0, 0xc0000aa1b0, 0x0, 0xc000064000, 0x68, 0x1a4, 0xc0005a7798, 0x98, ...)
	/agent/_work/1/s/go/src/github.com/Azure/secrets-store-csi-driver-provider-azure/pkg/provider/provider.go:276 +0x1798
github.com/Azure/secrets-store-csi-driver-provider-azure/pkg/server.(*CSIDriverProviderServer).Mount(0xc00000e450, 0xbebb40, 0xc00061a0c0, 0xc000642000, 0xc00000e450, 0x1, 0xc0000b0550)
	/agent/_work/1/s/go/src/github.com/Azure/secrets-store-csi-driver-provider-azure/pkg/server/server.go:53 +0x2f4
sigs.k8s.io/secrets-store-csi-driver/provider/v1alpha1._CSIDriverProvider_Mount_Handler.func1(0xbebb40, 0xc00061a0c0, 0xad0480, 0xc000642000, 0x0, 0x0, 0x4182f7, 0xfa5268)
	/agent/_work/1/s/go/pkg/mod/sigs.k8s.io/secrets-store-csi-driver@v0.0.21/provider/v1alpha1/service.pb.go:811 +0x89
github.com/Azure/secrets-store-csi-driver-provider-azure/pkg/utils.LogGRPC(0xbebb40, 0xc00061a0c0, 0xad0480, 0xc000642000, 0xc000314000, 0xc00000c030, 0x4716e7, 0x504325, 0xac6f00, 0xc00061a0c0)
	/agent/_work/1/s/go/src/github.com/Azure/secrets-store-csi-driver-provider-azure/pkg/utils/grpc.go:27 +0x26d
sigs.k8s.io/secrets-store-csi-driver/provider/v1alpha1._CSIDriverProvider_Mount_Handler(0xb06e40, 0xc00000e450, 0xbebb40, 0xc00061a0c0, 0xc000614120, 0xb4bf98, 0xbebb40, 0xc00061a0c0, 0xc000640000, 0x35e)
	/agent/_work/1/s/go/pkg/mod/sigs.k8s.io/secrets-store-csi-driver@v0.0.21/provider/v1alpha1/service.pb.go:813 +0x150
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000222380, 0xbf1318, 0xc000083200, 0xc000624000, 0xc0001a3b30, 0xf5fff8, 0x0, 0x0, 0x0)
	/agent/_work/1/s/go/pkg/mod/google.golang.org/grpc@v1.31.0/server.go:1180 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc000222380, 0xbf1318, 0xc000083200, 0xc000624000, 0x0)
	/agent/_work/1/s/go/pkg/mod/google.golang.org/grpc@v1.31.0/server.go:1503 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0000ac200, 0xc000222380, 0xbf1318, 0xc000083200, 0xc000624000)
	/agent/_work/1/s/go/pkg/mod/google.golang.org/grpc@v1.31.0/server.go:843 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/agent/_work/1/s/go/pkg/mod/google.golang.org/grpc@v1.31.0/server.go:841 +0x1fd
```

**What did you expect to happen:**
Not really sure, but not a nil pointer dereference.

**Which access mode did you use to access the Azure Key Vault instance:**
User identity (i.e. my personal credentials)

**Environment:**

- Secrets Store CSI Driver version: (use the image tag):
  - 0.0.19
- Azure Key Vault provider version: (use the image tag):
  - Not completely sure, can provide with some help if needed.
- Kubernetes version: (use `kubectl version` and `kubectl get nodes -o wide`):
  ```
  Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:11:29Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"darwin/amd64"}
  Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.9", GitCommit:"c1ad2bc44e0c7f19a9db0879f7182ff556a8e5b4", GitTreeState:"clean", BuildDate:"2021-05-19T22:27:45Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}  
  ```
- Cluster type: (e.g. AKS, aks-engine, etc):
  - AKS

**Comment by aramase** [comment]
@pjquirk Thank you for reporting the issue. We'll repro this and include the fix in the next release.

Are you using `objectType: cert` for this particular object?

**Comment by pjquirk** [comment]
@aramase Yep, that's correct.  Thanks!
